spring:
  datasource: 
    driver-class-name: com.mysql.cj.jdbc.Driver  #新版驱动需要用 cj.jdbc
    url: jdbc:mysql://localhost:3306/interview?useUnicode=true&characterEncoding=UTF-8&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8
    username: root   #dev环境
    password: 246810
  mvc: #url访问图片路径为 /qrcode/****
    static-path-pattern: /image/**
  resource: 
    static-locations: files:D://qrcode/
  jpa: 
    hibernate: 
      ddl-auto: update    #只能使用update!
      naming: 
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: false #服务时不显示
  devtools: 
    restart: 
      enabled: true #是否支持热部署
      exclude: WEB/INF/**    #不重启的目录
      additional-paths: src/main/java  #重启的目录
server:
  port: 8098
  #以下 ssl 认证通过nginx实现
  #port: 443
  #ssl: 
  #  key-store: classpath:mesqrcode.jks
  #  key-store-password: d1Kh1c65
  #  key-store-type: JKS
  #  key-alias: alias